; ============================================================
; SwitchProESP32
; ------------------------------------------------------------
; Plataforma : ESP32-WROOM-32
; Board      : DOIT ESP32 DEVKIT V1
;
; Framework:
;   ESP-IDF 4.4.7
;
; En esta etapa:
;   ESP-IDF puro.
;   Arduino NO se utiliza.
;
; Objetivo:
;   Preparar la base para implementar Bluetooth
;   Classic HID compatible con Nintendo Switch.
; ============================================================


[env:esp32dev]

; ------------------------------------------------------------
; Plataforma
; ------------------------------------------------------------

platform = espressif32
board = esp32dev


; ------------------------------------------------------------
; Framework
; ------------------------------------------------------------

framework = espidf


; ------------------------------------------------------------
; SDKConfig
; ------------------------------------------------------------

board_build.sdkconfig = sdkconfig.esp32dev


; ------------------------------------------------------------
; Monitor serial
; ------------------------------------------------------------

monitor_speed = 115200


; ------------------------------------------------------------
; Velocidad de carga
; ------------------------------------------------------------

upload_speed = 921600